# Configuração do SonarCloud para o Projeto PHM Tradutor Universal

# Chaves de Organização e Projeto (Caso sejam diferentes no seu painel do SonarCloud, ajuste aqui)
sonar.organization=rodrigotejos
sonar.projectKey=rodrigotejos_Project-Hail-Mary-Universal-Translator
sonar.projectName=Project-Hail-Mary-Universal-Translator

# Pastas de código-fonte e testes
sonar.sources=src
sonar.tests=tests

# Configuração de linguagem (Python)
sonar.language=py
sonar.python.version=3.12

# Caminho do relatório de cobertura de código gerado pelo pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Codificação dos arquivos
sonar.sourceEncoding=UTF-8
